# Generated by Django 4.2.4 on 2023-08-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzeDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.companysensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно считано'), ('problem', 'Возникли проблемы'), ('critical', 'Критическое значение')], default='success', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('air_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('surface_soil_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_temperature_5m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_temperature_10m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzeDashboard.building')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor')),
            ],
        ),
    ]
