# Generated by Django 4.2.4 on 2023-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
