# Generated by Django 4.2.4 on 2023-08-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow')], default='green', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_region', models.IntegerField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('total_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dry_soil_density', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frozen_soil_thermal_conductivity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('thawed_soil_thermal_conductivity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frozen_soil_specific_heat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('thawed_soil_specific_heat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('soil_density', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_air_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_surface_soil_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_soil_temperature_5m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_soil_temperature_10m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_air_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_surface_soil_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_soil_temperature_5m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_soil_temperature_10m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzeDashboard.building')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='research_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzeDashboard.research')),
            ],
        ),
    ]
