# Generated by Django 4.2.4 on 2023-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='condition_image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
        migrations.AddField(
            model_name='building',
            name='frozen_water_amount',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
        migrations.AddField(
            model_name='building',
            name='view_image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
    ]
