# Generated by Django 4.2.4 on 2023-08-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeDashboard', '0002_building_condition_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='frozen_water_amount',
            new_name='frozen_water_amount_image',
        ),
        migrations.AddField(
            model_name='building',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
    ]
